### ISSUE TITLE
bluemix-cloudbase-init Upstreaming

### ISSUE THREAD

**Issue by alexpilotti** [softlayer/bluemix-cloudbase-init#2]
Would you guys be interested in merging this upstream in Cloudbase-Init?

**Comment by allmightyspiff** [comment]
@alexpilotti Sure, I'll look into it what would be involved in getting this added to the upstream cloudbase-init project.

**Comment by allmightyspiff** [comment]
After looking into this a bit, I'm not sure if there would be a lot of value with merging this small project upstream.

My reasoning is that:

1. ~~Bluemix~~ Classic infrastructure Virtual Servers should already have cloudbase-init + this project installed by default, so anyone provisioning a server on IBM Cloud classic infrastructure should be good to go already, no worries there.
2. Our newer virtual servers ([Virtual Private Cloud](https://cloud.ibm.com/docs/vpc)) use the built in `ConfigDriveService` so this service wouldn't be needed for those.
3. I'd have to rename this project, since bluemix is a dead name at this point. Not a huge problem of course, but a bit of work given that I think the only people who would need this as part of the base cloudbase-init package would be users setting up windows outside of our provisioning system.


Anyway, to make it a bit more clear that IBM supports cloudbase-init, I updated the readme with some documentation we have on the subject. 
To be clear, my only real objection to doing the work required to get this part of cloudbase-init is that I'm not sure if anyone is installing this project manually as is. I'm not an expert on this though, so if there are users whos life would be made easier with this as part of the upstream package, I'd be happy to change my mind.

**Comment by alexpilotti** [comment]
@allmightyspiff thanks for all the detailed clarifications. I agree, given that this metadata provider is only needed for legacy use cases it wouldn’t be particularly useful to upstream it. Please let me know if you have any feedback or feature requests for Cloudbase-Init, our goal is to make sure it works well on all popular public or private cloud scenarios.
